name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Check for packaging errors
        uses: kirkeaton/action-publint@2f47f042fffcbd4c2d52f4a2da83b88b0ebfdf80 # v2.0.17
